### ISSUE TITLE
No package on PyPI

### ISSUE THREAD

**Issue by webmaven** [pragmaticbadger/django-privatebeta#7]
Should be self-explanatory... ;-)

**Comment by zyegfryed** [comment]
A new release should be opportune too :)

**Comment by lizrice** [comment]
Hello. It would be great if the package on PyPI was the latest code (I like that ENABLE_BETA setting)! I'd volunteer to do it myself but presumably the package owner on PyPI has to do it?  Shout if there's anything I can do to help.

**Comment by webmaven** [comment]
Closing as out of date.
